CREATE TABLE IF NOT EXISTS accounts (
    id         SERIAL PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    balance    BIGINT NOT NULL DEFAULT 0,
    currency   VARCHAR(3) NOT NULL DEFAULT 'COP',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);