ALTER TABLE transactions
ADD COLUMN from_currency VARCHAR(3) NOT NULL DEFAULT 'COP',
ADD COLUMN to_currency VARCHAR(3) NOT NULL DEFAULT 'COP',
ADD COLUMN exchange_rate NUMERIC(19,6) NOT NULL DEFAULT 1,
ADD COLUMN converted_amount BIGINT NOT NULL DEFAULT 0;